Repository FRONT-END-BOOTCAMP-PLUS-3/tododong, pull requests merged in 2025-04, with the labels that each got.

#66 🎨 design: 반응형 디자인 추가
  app/(anon)/schedule/components/date-picker/DatePicker.module.scss
  app/(anon)/schedule/components/date-picker/DatePicker.tsx
  app/(anon)/schedule/components/date-picker/calendar-custom.scss
  app/(anon)/schedule/components/game-card/GameCard.module.scss
  app/(anon)/schedule/page.module.scss
  components/footer/Footer.module.scss
  components/game-status-tag/GameStatusTag.module.scss
  components/header/Header.module.scss
  components/team/Team.module.scss
  styles/base/_default.scss
  styles/utils/_mixins.scss
  styles/utils/_variables.scss
Labels: 🎨 design

#81 ♻️ refactor : 비디오 페이지 react-query 및 반응형 추가
  app/(anon)/game/[game-id]/layout.module.scss
  app/(anon)/game/[game-id]/layout.tsx
  app/(anon)/game/[game-id]/videos/components/YoutubeVideoCard.module.scss
  app/(anon)/game/[game-id]/videos/components/YoutubeVideoCard.tsx
  app/(anon)/game/[game-id]/videos/page.module.scss
  app/(anon)/game/[game-id]/videos/page.tsx
  app/layout.tsx
  components/query-provider/QueryProvider.tsx
  package.json
  pnpm-lock.yaml
  styles/utils/_mixins.scss
Labels: 🎨 design, ♻️ refactor

#88 ✨ feat : Not-found 페이지
  app/(anon)/layout.tsx
  app/layout.module.scss
  app/layout.tsx
  app/not-found.module.scss
  app/not-found.tsx
Labels: ✨ feat, 🔧 chore

#90 ♻️ refactor : Header, Footer 렌더링 여부 로직 위치 변경
  app/(anon)/layout.tsx
  app/layout.tsx
  components/footer/Footer.tsx
  components/header/Header.tsx
Labels: ♻️ refactor

#91 ♻️ refactor: react-query, 실시간 데이터, 반응형 작업
  app/(anon)/game/[game-id]/components/chat/ChatSection.module.scss
  app/(anon)/game/[game-id]/components/game-status/GameStatusSection.module.scss
  app/(anon)/game/[game-id]/components/game-status/GameStatusSection.tsx
  app/(anon)/game/[game-id]/components/providers/ReactQueryProviders.tsx
  app/(anon)/game/[game-id]/components/today/TodayGameCard.module.scss
  app/(anon)/game/[game-id]/components/today/TodayGameSection.module.scss
  app/(anon)/game/[game-id]/components/today/TodayGameSection.tsx
  app/(anon)/game/[game-id]/components/today/swiper.scss
  app/(anon)/game/[game-id]/layout.tsx
  application/usecases/game/game-detail/dto/gameDetailDto.ts
  application/usecases/game/game-detail/getGameDetailUsecase.ts
Labels: ♻️ refactor

#92 ♻️ refactor: 게임 일정 데이터 페칭 리팩토링
  app/(anon)/schedule/components/date-picker/DatePicker.tsx
  app/(anon)/schedule/page.tsx
  app/api/schedule/route.ts
  application/usecases/schedule/readScheduledGameCountListUsecase.ts
  domain/repositories/GameRepository.ts
  infrastructure/repositories/prisma/PrGameRepository.ts
  package.json
  pnpm-lock.yaml
  utils/convertGameStatus.ts
  utils/index.ts
Labels: ♻️ refactor

#97 ✨ feat: schedule 페이지에서 유효하지 않은 date 쿼리 파라미터 대응을 위한 404 페이지 처리 추가
  app/(anon)/schedule/not-found.module.scss
  app/(anon)/schedule/not-found.tsx
  app/(anon)/schedule/page.tsx
Labels: ✨ feat

#95 🎨 feat: ChatSection 반응형 바텀시트 구현
  app/(anon)/game/[game-id]/components/chat/ChatSection.module.scss
  app/(anon)/game/[game-id]/components/chat/ChatSection.tsx
  app/layout.tsx
  next.config.ts
  package.json
  pnpm-lock.yaml
  providers/MediaProvider.tsx
  stores/mediaStore.ts
  styles/utils/_mixins.scss
Labels: ✨ feat, 🎨 design
